# Generated by Django 5.0.4 on 2024-05-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='undef', max_length=255)),
                ('cover_letter', models.CharField(default='undef', max_length=255)),
                ('status', models.CharField(default='undef', max_length=255)),
                ('full_name', models.CharField(default='undef', max_length=255)),
                ('street_name', models.CharField(default='undef', max_length=255)),
                ('house_number', models.CharField(default='undef', max_length=255)),
                ('city', models.CharField(default='undef', max_length=255)),
                ('country', models.CharField(default='undef', max_length=255)),
                ('postal_code', models.CharField(default='undef', max_length=255)),
                ('job_seeker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_work', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='undef', max_length=255)),
                ('description', models.CharField(blank=True, default='undef', max_length=255)),
                ('salary', models.CharField(default='undef', max_length=255)),
                ('requirements', models.CharField(default='undef', max_length=255)),
                ('category', models.CharField(default='undef', max_length=255)),
                ('employer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.employer')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Jobs.joblisting'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobapplication')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.joblisting')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('may_be_contacted', models.BooleanField()),
                ('role', models.CharField(max_length=255)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobapplication')),
            ],
        ),
    ]
