# Generated by Django 5.0.4 on 2024-05-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_letter', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.joblisting')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobapplication')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.joblisting')),
            ],
        ),
    ]
