# Generated by Django 5.0.4 on 2024-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='time_type',
            field=models.CharField(blank=True, default='undef', max_length=255),
        ),
    ]
