# Generated by Django 5.0.4 on 2024-05-10 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='city',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='country',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='house_number',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_seeker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.jobseeker'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='postal_code',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='street_name',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='category',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='employer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.employer'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Jobs.joblisting'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='title',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.CharField(blank=True, default='undef', max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='requirements',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(default='undef', max_length=255),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_work', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('may_be_contacted', models.BooleanField()),
                ('role', models.CharField(max_length=255)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobapplication')),
            ],
        ),
    ]
