# Generated by Django 5.0.4 on 2024-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_joblisting_time_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
