# Generated by Django 5.0.4 on 2024-05-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_joblisting_due_date_joblisting_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
