# Generated by Django 5.0.4 on 2024-05-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_joblisting_is_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='email_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='may_be_contacted',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
