# Generated by Django 5.0.4 on 2024-05-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_alter_jobapplication_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='house_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
