# Generated by Django 5.0.4 on 2024-05-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='No Name', max_length=255),
        ),
    ]
