# Generated by Django 5.0.4 on 2024-05-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_jobseeker_user_ptr_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobseeker',
            options={},
        ),
        migrations.AlterModelManagers(
            name='employer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='jobseeker',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='employer',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.user'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
    ]
